Prevent failing if cannot set 'update-available' feature
(cherry picked from commit b95f2716b6c48a1ff04032187ab5b81ecaa9d9ba)

diff --git a/dom0-updates/qubes-dom0-update b/dom0-updates/qubes-dom0-update
--- a/dom0-updates/qubes-dom0-update
+++ b/dom0-updates/qubes-dom0-update
@@ -266,9 +266,15 @@ elif [ -f /var/lib/qubes/updates/repodata/repomd.xml ]; then
             dnf "${YUM_OPTS[@]}" $YUM_ACTION
         fi
     fi
-    dnf -q check-update && qvm-features dom0 updates-available ''
+    if dnf -q check-update; then
+        if ! qvm-features dom0 updates-available ''; then
+            echo "*** WARNING: cannot set feature 'updates-available'" >&2
+        fi
+    fi
 else
-    qvm-features dom0 updates-available ''
+    if ! qvm-features dom0 updates-available ''; then
+        echo "*** WARNING: cannot set feature 'updates-available'" >&2
+    fi
     echo "No updates available" >&2
     if [ "$GUI" == "1" ]; then
         zenity --info --title='Dom0 updates' --text='No updates available'
