qubes-dom0-update: print message when updates are available
With UpdateVM output hidden by default, --check-only results in no
message at all (only exit code). Print a message from qubes-dom0-update
script directly in this case.

diff --git a/dom0-updates/qubes-dom0-update b/dom0-updates/qubes-dom0-update
--- a/dom0-updates/qubes-dom0-update
+++ b/dom0-updates/qubes-dom0-update
@@ -275,6 +275,15 @@ qvm-run "${QVMRUN_OPTS[@]}" -- "$UPDATEVM" "$CMD" < /dev/null
 
 RETCODE=$?
 if [[ "$REMOTE_ONLY" = '1' ]] || [ "$RETCODE" -ne 0 ]; then
+    if [ "$CHECK_ONLY" = '1' ]; then
+        if [ "$RETCODE" -eq 100 ]; then
+            echo "There are dom0 updates available" >&2
+        elif [ "$RETCODE" -eq 0 ]; then
+            echo "No dom0 updates available" >&2
+        else
+            echo "Failed to check for dom0 updates" >&2
+        fi
+    fi
     exit $RETCODE
 fi
 # Wait for download completed
